name: temp_place
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  font_awesome_flutter: ^10.4.0
  flutter_screenutil: ^5.7.0
  flutter_rating_bar: ^4.0.0
  pin_code_fields: ^7.4.0
  intl: ^0.18.0
  animations: ^2.0.7
  google_fonts: ^4.0.3  
  fl_chart: ^0.61.0
  get: ^4.6.5
  timeline_tile: ^2.0.0
  get_storage: ^2.1.1
  
  skeletons: ^0.0.3
  cached_network_image: ^3.0.0
  internet_connection_checker: ^0.0.1+2
  lottie: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  # flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
      - family: WorkSans
        fonts:
            - asset: assets/fonts/WorkSans-Regular.ttf
            - asset: assets/fonts/WorkSans-Medium.ttf
              weight: 500
            - asset: assets/fonts/WorkSans-SemiBold.ttf
              weight: 600
            - asset: assets/fonts/WorkSans-Bold.ttf
              weight: 700
      - family: Roboto
        fonts:
            - asset: assets/fonts/Roboto-Bold.ttf
            - asset: assets/fonts/Roboto-Regular.ttf
            - asset: assets/fonts/Roboto-Medium.ttf
              weight: 400